---
output:
  html_document: default
  pdf_document: default
---
```{r echo=FALSE, eval=TRUE, results='hide',include=FALSE}
library(TMB)
library(mgcv)
library(Matrix)
```


## **North East Arctic Cod** 
In this example you learn:

* How to run SAM with XSAM-options for NEAcod
* How to set quotas for NEAcod with XSAM options

If you want to read trough the implementation of SAM, we recomend you look at this case study which elaborates a simplefied version of [SAM](https://github.com/skaug/tmb-case-studies/tree/master/SAM).


To run a SAM model can be divided into five standard steps:

1. Read data
2. Set up SAM data
3. Set up configurations
4. Define parameters
5. Fit SAM

In this example we illustrate how to modify these parts to use settings from XSAM.

***
### Fit current used SAM model

<details>  
  <summary>Read data</summary>
```r
  cn<-read.ices("data/NEAcod/cn.dat")
  cw<-read.ices("data/NEAcod/cw.dat")
  dw<-read.ices("data/NEAcod/dw.dat")
  lf<-read.ices("data/NEAcod/lf.dat")
  lw<-read.ices("data/NEAcod/lw.dat")
  mo<-read.ices("data/NEAcod/mo.dat")
  nm<-read.ices("data/NEAcod/nm.dat")
  pf<-read.ices("data/NEAcod/pf.dat")
  pm<-read.ices("data/NEAcod/pm.dat")
  sw<-read.ices("data/NEAcod/sw.dat")
  surveys<-read.ices("data/NEAcod/survey.dat")
```
</details>

<details>  
  <summary>Setup SAM data</summary>
```r
  dat<-setup.sam.data(surveys=surveys,
                      residual.fleet=cn, 
                      prop.mature=mo, 
                      stock.mean.weight=sw, 
                      catch.mean.weight=cw, 
                      dis.mean.weight=dw, 
                      land.mean.weight=lw,
                      prop.f=pf, 
                      prop.m=pm, 
                      natural.mortality=nm, 
                      land.frac=lf)
```
</details>

<details>  
  <summary>Set configurations</summary>
```r
  conf<-loadConf(dat,"scripts/NEAcod/model.cfg", patch=TRUE)
```
</details>

<details>  
  <summary>Set parameters</summary>
```r
  par<-defpar(dat,conf)
```
</details>

<details>  
  <summary>Fit SAM</summary>
```r
  fit<-sam.fit(dat,conf,par)
```
</details>


***

### Fit current used SAM model with XSAM options
First we read the data and configurations as for currently used SAM.
<details>  
  <summary>Read data</summary>
```r
  cn<-read.ices("data/NEAcod/cn.dat")
  cw<-read.ices("data/NEAcod/cw.dat")
  dw<-read.ices("data/NEAcod/dw.dat")
  lf<-read.ices("data/NEAcod/lf.dat")
  lw<-read.ices("data/NEAcod/lw.dat")
  mo<-read.ices("data/NEAcod/mo.dat")
  nm<-read.ices("data/NEAcod/nm.dat")
  pf<-read.ices("data/NEAcod/pf.dat")
  pm<-read.ices("data/NEAcod/pm.dat")
  sw<-read.ices("data/NEAcod/sw.dat")
  surveys<-read.ices("data/NEAcod/survey.dat")
```
</details>

<details>  
  <summary>Set currently used configurations</summary>
```r
  conf<-loadConf(dat,"scripts/NEAcod/model.cfg", patch=TRUE)
```
</details>

#### Fit current used SAM model with external variance structures
We have some knowledge of the uncertainty estimates of the commercial catches and the survey FLT15 from outside of the assessment model. 
<details>  
  <summary>Read variance estimates of catches ad FLT15</summary>
```r
  varC = as.matrix(read.table("data/NEAcod/variances/varCatch.txt", sep = " "))
  varS1 = as.matrix(read.table("data/NEAcod/variances/varFLT15Cod.txt", sep = " "))
```
</details>

<details>  
  <summary>Set the variance estimates of catches ad FLT15 as invese weight attributes to the surveys</summary>
```r
  attributes(cn)$weight = 1/varC
  attributes(surveys[[1]])$weight = 1/varS1
```
</details>

<details>  
  <summary>Setup SAM data</summary>
```r
  dat<-setup.sam.data(surveys=surveys,
                      residual.fleet=cn, 
                      prop.mature=mo, 
                      stock.mean.weight=sw, 
                      catch.mean.weight=cw, 
                      dis.mean.weight=dw, 
                      land.mean.weight=lw,
                      prop.f=pf, 
                      prop.m=pm, 
                      natural.mortality=nm, 
                      land.frac=lf)
```
  <em>Note: The external variance estimates of the catches and FLT15 are now included in `dat$weigth`.</em>
</details>

<details>  
  <summary>Set parameters</summary>
```r
  par<-defpar(dat,conf)
```
</details>

<details>  
  <summary>Fit SAM</summary>
```r
  fit<-sam.fit(dat,conf,par)
```
</details>


#### Use constant mean recruitmen option

<details>  
  <summary>Modify configurations, set parameters and run SAM</summary>
```r
  conf$stockRecruitmentModelCode = 3
  par<-defpar(dat,conf)
  fit<-sam.fit(dat,conf,par)
```
  <em>Note: The function `defpar(dat,conf)` sees that we want to use the mean recruitmen option, and set parameters accordingly. We are also able to select breakpoints were we say that there can be different mean recruitment before and after given years. Such break points can be included in `conf$constRecBreaks`</em>
</details>

#### Use separable F structure

<details>  
  <summary>Modify configurations, set parameters and run SAM</summary>
```r
  conf$corFlag = 3
  par<-defpar(dat,conf)
  fit3<-sam.fit(dat,conf,par)
```
  <em>Note: The function `defpar(dat,conf)` sees that we want to use the separable structure for fishing mortality, and set parameters accordingly.</em>
</details>

#### Remove the process error term

<details>  
  <summary>Modify initial values of the process error to a value approximately zero</summary>
```r
  par$logSdLogN = c(-0.35,-6)
```
</details>

<details>  
  <summary>Inform that we do not want to estimate the process error</summary>
```r
  map = list(logSdLogN = as.factor(c(0,NA)))
```
</details>

<details>  
  <summary>Fit SAM</summary>
```r
  fit<-sam.fit(dat,conf,par,map = map)
```
  <em>Note: The `map` variable informs `sam.fit` that the process error are to be kept to its initial value, which is approximately zero.</em>
</details>





***

## Simplefied NEAcod quotas for 2020
The target level of exploration is calculated with the following formula:
\begin{align}
  F_{tr}=
  \begin{cases}
  \frac{\text{SSB}}{B_{pa}} F_{msy} ,& \text{if } \text{SSB} \leq B_{pa}  \\
  F_{msy} ,& \text{if } \text{B}_{pa} < \text{SSB} \leq 2B_{pa}  \\
  F_{msy} (1+0.5\frac{\text{SSB} - 2\text{B}_{pa}}{\text{B}_{pa}}) ,& \text{if } 2\text{B}_{pa} < \text{SSB} \leq 3B_{pa}  \\
  1.5F_{msy} ,& \text{if }  3\text{B}_{pa} \leq \text{SSB} 
  \end{cases}
\end{align}
where $F_{msy} = 0.4$ and $\text{B}_{pa} = 460000$ tonnes.

<details>  
  <summary>Forecast SSB in beginning of year 2020</summary>
The estimated catch in 2019 is 697 kt, and we can forcast the SSB in 2020 with use of the `forecast` function in SAM.
```r
  set.seed(12345)
  forecast(fit,catchval = c(697000,0,0,0))
```
This gives an estimated SSB of 1386647. 

</details>


<details>  
  <summary>Calculate $\text{F}_{tr}$</summary>
  Since the estimated SSB in year 2020 is 1386647, we have that $F_{tr} = 1.5\text{F}_{msy} = 0.6$
</details>

<details>  
  <summary>Forecast catches in year 2020 to 2022 with $\text{F} = \text{F}_{tr}$</summary>
 We can then forecast the catches with $\text{F} = \text{F}_{tr} =  0.6$ in years 2020,2021 and 2022 with the `forecast` function in SAM:

```r
  set.seed(12345)
  forecast(fit,catchval = c(697000,NA,NA,NA), fval = c(NA,0.6,0.6,0.6))
```

The average catch in years 2020 to 2022 is 778270 tonns of cod, which is used as the quota advice.
</details>

  
***


***

## Estimate weights inside SAM and compare with external weights

Remeber that the variance estimates are in this example smoothed by the following procedure. Let $\mu_{a,y}$ be the observation for age $a$ at year $y$ on natural scale, and let $v_{a,y}$ be the correspondning variance. We assume that
\begin{align}
\log v_{a,y} = \alpha + \beta \log(\mu_{a,y}). 
\end{align}
It is futher estimated that $\alpha = 1.085$ and $\beta = 1.475$ outside of the assessment model, and these two parameters are used combined with observations to create `varC` and `varS1`.

The equation above can be included internally in SAM. To estimate weights internally in SAM we need to install a development version of SAM. The development version can be installed by writing:

```r
devtools::install_github("fishfollower/SAM/stockassessment",ref = "varMeanLink")
```

set the configurations to use internal weighting with the `meanWeigthObsV` option.

```r
  conf$meanWeightObsV = 1
  conf$meanVarObsLink = conf$keyVarObs
  par<-defpar(dat,conf)
  fit<-sam.fit(dat,conf,par)
```
<em>Note: Internally in SAM, $\log(\mu_{a,y})$ is replaced with the expected observation for age $a$ at year $y$.</em>

By estimating the smooting paramters inside SAM we get $\alpha = 2.67$ and $\beta = 1.443$. Note that the $\alpha$-parameter differ quite a lot if it is estimated inside or outside of SAM. This is reasonable since the external variance parameters are further scaled in the assessment model. 


***



